version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: mysourcing-db-local
    environment:
      POSTGRES_DB: mysourcing_pulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_local:
