import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const seedBanks = async () => {
  console.log('🏦 Seeding banks catalog...');
  
  const banks = [
    { code: '002', name: 'Banco Nacional de México S.A., Institución de Banca Múltiple, Grupo Financiero Banamex', shortName: 'BANAMEX' },
    { code: '006', name: 'Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', shortName: 'BANCOMEXT' },
    { code: '009', name: 'Banco Nacional de Obras y Servicios Públicos, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', shortName: 'BANOBRAS' },
    { code: '012', name: 'BBVA México, S.A., Institución de Banca Múltiple, Grupo Financiero BBVA México', shortName: 'BBVA MÉXICO' },
    { code: '014', name: 'Banco Santander México, S.A., Institución de Banca Múltiple, Grupo Financiero Santander México', shortName: 'SANTANDER' },
    { code: '019', name: 'Banco Nacional del Ejército, Fuerza Aérea y Armada, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', shortName: 'BANJERCITO' },
    { code: '021', name: 'HSBC México, S.A., Institución de Banca Múltiple, Grupo Financiero HSBC', shortName: 'HSBC' },
    { code: '030', name: 'Banco del Bajío, S.A., Institución de Banca Múltiple', shortName: 'BAJÍO' },
    { code: '032', name: 'IXE Banco, S.A., Institución de Banca Múltiple, IXE Grupo Financiero', shortName: 'IXE' },
    { code: '036', name: 'Banco Inbursa, S.A., Institución de Banca Múltiple, Grupo Financiero Inbursa', shortName: 'INBURSA' },
    { code: '037', name: 'Banco Interacciones, S.A., Institución de Banca Múltiple', shortName: 'INTERACCIONES' },
    { code: '042', name: 'Banco Mifel, S.A., Institución de Banca Múltiple, Grupo Financiero Mifel', shortName: 'MIFEL' },
    { code: '044', name: 'Scotiabank Inverlat, S.A., Institución de Banca Múltiple, Grupo Financiero Scotiabank Inverlat', shortName: 'SCOTIABANK' },
    { code: '058', name: 'BanRegio S.A., Institución de Banca Múltiple, Banregio Grupo Financiero', shortName: 'BANREGIO' },
    { code: '059', name: 'Banco Invex, S.A., Institución de Banca Múltiple, Invex Grupo Financiero', shortName: 'INVEX' },
    { code: '060', name: 'Bansi, S.A., Institución de Banca Múltiple', shortName: 'BANSI' },
    { code: '062', name: 'Banca Afirme, S.A., Institución de Banca Múltiple', shortName: 'AFIRME' },
    { code: '072', name: 'Banco Mercantil del Norte, S.A., Institución de Banca Múltiple, Grupo Financiero Banorte', shortName: 'BANORTE' },
    { code: '102', name: 'The Royal Bank of Scotland México, S.A., Institución de Banca Múltiple', shortName: 'RBS' },
    { code: '103', name: 'American Express Bank (México), S.A., Institución de Banca Múltiple', shortName: 'AMERICAN EXPRESS' },
    { code: '106', name: 'Bank of America México, S.A., Institución de Banca Múltiple', shortName: 'BAMSA' },
    { code: '108', name: 'Bank of Tokyo-Mitsubishi UFJ (México), S.A.', shortName: 'MUFG' },
    { code: '110', name: 'Banco J.P. Morgan, S.A., Institución de Banca Múltiple, J.P. Morgan Grupo Financiero', shortName: 'JP MORGAN' },
    { code: '112', name: 'Banco Monex, S.A., Institución de Banca Múltiple', shortName: 'BMONEX' },
    { code: '113', name: 'Banco Ve Por Mas, S.A., Institución de Banca Múltiple', shortName: 'VE POR MAS' },
    { code: '116', name: 'ING Bank (México), S.A., Institución de Banca Múltiple, ING Grupo Financiero', shortName: 'ING' },
    { code: '124', name: 'Deutsche Bank México, S.A., Institución de Banca Múltiple', shortName: 'DEUTSCHE' },
    { code: '126', name: 'Banco Credit Suisse (México), S.A., Institución de Banca Múltiple, Grupo Financiero Credit Suisse (México)', shortName: 'CREDIT SUISSE' },
    { code: '127', name: 'Banco Azteca, S.A., Institución de Banca Múltiple', shortName: 'AZTECA' },
    { code: '128', name: 'Banco Autofin México, S.A., Institución de Banca Múltiple', shortName: 'AUTOFIN' },
    { code: '129', name: 'Barclays Bank México, S.A., Institución de Banca Múltiple, Grupo Financiero Barclays México', shortName: 'BARCLAYS' },
    { code: '130', name: 'Banco Compartamos, S.A., Institución de Banca Múltiple', shortName: 'COMPARTAMOS' },
    { code: '131', name: 'Banco Ahorro Famsa, S.A., Institución de Banca Múltiple', shortName: 'FAMSA' },
    { code: '132', name: 'Banco Multiva, S.A., Institución de Banca Múltiple, Multivalores Grupo Financiero', shortName: 'MULTIVA' },
    { code: '133', name: 'Banco Actinver, S.A., Institución de Banca Múltiple, Grupo Financiero Actinver', shortName: 'ACTINVER' },
    { code: '134', name: 'Banco Wal-Mart de México Adelante, S.A., Institución de Banca Múltiple', shortName: 'WALMART' },
    { code: '135', name: 'Nacional Financiera, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', shortName: 'NAFIN' },
    { code: '136', name: 'Banco Regional de Monterrey, S.A., Institución de Banca Múltiple, Banregio Grupo Financiero', shortName: 'REGIONAL' },
    { code: '137', name: 'BanCoppel, S.A., Institución de Banca Múltiple', shortName: 'BANCOPPEL' },
    { code: '138', name: 'ABC Capital, S.A., Institución de Banca Múltiple', shortName: 'ABC CAPITAL' },
    { code: '139', name: 'UBS Bank México, S.A., Institución de Banca Múltiple, UBS Grupo Financiero', shortName: 'UBS BANK' },
    { code: '140', name: 'ConsuBanco, S.A., Institución de Banca Múltiple', shortName: 'CONSUBANCO' },
    { code: '141', name: 'Volkswagen Bank, S.A., Institución de Banca Múltiple', shortName: 'VOLKSWAGEN' },
    { code: '143', name: 'CIBANCO, S.A.', shortName: 'CIBanco' },
    { code: '145', name: 'Banca Base, S.A., Institución de Banca Múltiple', shortName: 'BBASE' },
    { code: '147', name: 'Bankaool, S.A., Institución de Banca Múltiple', shortName: 'BANKAOOL' },
    { code: '148', name: 'Banco PagaTodo, S.A., Institución de Banca Múltiple', shortName: 'PAGATODO' },
    { code: '150', name: 'Banco Inmobiliario Mexicano, S.A., Institución de Banca Múltiple', shortName: 'BIM' },
    { code: '151', name: 'Fundación Dondé Banco, S.A., Institución de Banca Múltiple', shortName: 'DONDE' },
    { code: '152', name: 'Bancrea, S.A., Institución de Banca Múltiple', shortName: 'BANCREA' },
    { code: '154', name: 'Banco Progreso Chihuahua, S.A., Institución de Banca Múltiple', shortName: 'PROGRESO' },
    { code: '155', name: 'Banco Sabadell, S.A., Institución de Banca Múltiple', shortName: 'SABADELL' },
    { code: '156', name: 'Banco Shinhan de México, S.A., Institución de Banca Múltiple', shortName: 'SHINHAN' },
    { code: '157', name: 'Banco S3 México, S.A., Institución de Banca Múltiple', shortName: 'BANCO S3' },
    { code: '158', name: 'Mizuho Bank México, S.A.', shortName: 'MIZUHO BANK' },
    { code: '159', name: 'Banco KEB Hana México, S.A.', shortName: 'KEB HANA MEXICO' },
    { code: '166', name: 'Banco del Bienestar, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', shortName: 'BIENESTAR' },
    { code: '168', name: 'Sociedad Hipotecaria Federal, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', shortName: 'HIPOTECARIA FEDERAL' },
    { code: '170', name: 'Banco Mercurio, S.A., Institución de Banca Múltiple', shortName: 'MERCURIO' },
    { code: '600', name: 'Monexcasa de Bolsa, S.A. de C.V., Monex Grupo Financiero', shortName: 'MONEXCB' },
    { code: '601', name: 'Intercam Casa de Cambio, S.A. de C.V.', shortName: 'INTERCAM' },
    { code: '602', name: 'GBM Grupo Bursátil Mexicano, S.A. de C.V., Casa de Bolsa', shortName: 'GBM' },
    { code: '605', name: 'Value, S.A. de C.V. Casa de Bolsa', shortName: 'VALUE' },
    { code: '606', name: 'Estructuradores del Mercado de Valores Casa de Bolsa, S.A. de C.V.', shortName: 'CB BASE' },
    { code: '607', name: 'Casa de Cambio Tiber, S.A. de C.V.', shortName: 'TIBER' },
    { code: '608', name: 'Vector Casa de Bolsa, S.A. de C.V.', shortName: 'VECTOR' },
    { code: '610', name: 'B y B, Casa de Cambio, S.A. de C.V.', shortName: 'B&B' },
    { code: '611', name: 'Acciones y Valores Banamex, S.A. de C.V., Casa de Bolsa', shortName: 'ACCIVAL BANAMEX' },
    { code: '613', name: 'Kuspit Casa de Bolsa, S.A. de C.V.', shortName: 'KUSPIT' },
    { code: '614', name: 'Profuturo G.N.P., S.A. de C.V., Afore', shortName: 'PROFUTURO' },
    { code: '615', name: 'SD. Indeval, S.A. de C.V.', shortName: 'SD INDEVAL' },
    { code: '616', name: 'Finamex Casa de Bolsa, S.A. de C.V.', shortName: 'FINAMEX' },
    { code: '617', name: 'CI Casa de Bolsa, S.A. de C.V.', shortName: 'CI BOLSA' },
    { code: '618', name: 'Casa de Bolsa Ve Por Mas, S.A. de C.V., Grupo Financiero Ve Por Mas', shortName: 'VALMEX' },
    { code: '619', name: 'Casa de Bolsa Mapfre, S.A. de C.V.', shortName: 'MAPFRE' },
    { code: '620', name: 'Profuturo Afore, S.A. de C.V.', shortName: 'PROFUTURO CB' },
    { code: '621', name: 'CB ACTINVER, S.A. de C.V.', shortName: 'ACTINVER CB' },
    { code: '622', name: 'OACTIN, S.A. de C.V., Fondo de Inversión', shortName: 'OACTIN' },
    { code: '623', name: 'Skandia Vida, S.A. de C.V.', shortName: 'SKANDIA' },
    { code: '624', name: 'Consultoría Internacional Casa de Cambio, S.A. de C.V.', shortName: 'CBDEUTSCHE' },
    { code: '625', name: 'Deutsche Securities, S.A. de C.V. CASA DE BOLSA', shortName: 'DEUTSCHE' },
    { code: '626', name: 'Zurich Compañía de Seguros, S.A.', shortName: 'ZURICH' },
    { code: '627', name: 'Zurich Vida, Compañía de Seguros, S.A.', shortName: 'ZURICHVI' },
    { code: '628', name: 'Hipotecaria Su Casita, S.A. de C.V.', shortName: 'SU CASITA' },
    { code: '629', name: 'Intercam Fondos, S.A. de C.V.', shortName: 'INTERCAM FONDOS' },
    { code: '630', name: 'C.B. JP Morgan, S.A. de C.V.', shortName: 'CB JPMORGAN' },
    { code: '631', name: 'Finaccess México, S.A. de C.V.', shortName: 'FINACCESS' },
    { code: '632', name: 'Assets Custody International, S.A. de C.V.', shortName: 'ASSETS' },
    { code: '633', name: 'J.P. Morgan Operadora de Fondos, S.A. de C.V.', shortName: 'JPMORGAN FONDOS' },
    { code: '634', name: 'Reforma-Izetac, S.A. de C.V.', shortName: 'REFORMA' },
    { code: '636', name: 'Order Express Casa de Cambio, S.A. de C.V. AAC', shortName: 'ORDER' },
    { code: '637', name: 'Akala, S.A. de C.V., Sociedad Financiera Popular', shortName: 'AKALA' },
    { code: '638', name: 'JP Morgan Casa de Bolsa, S.A. de C.V., J.P. Morgan Grupo Financiero', shortName: 'JPMORGAN CB' },
    { code: '640', name: 'Operadora de Recursos Reforma, S.A. de C.V.', shortName: 'OP REFORMA' },
    { code: '646', name: 'Sistema de Transferencias y Pagos STP, S.A. de C.V. SOFOM E.N.R.', shortName: 'STP' },
    { code: '647', name: 'Telecomunicaciones de México', shortName: 'TELECOMM' },
    { code: '648', name: 'Evercore Casa de Bolsa, S.A. de C.V.', shortName: 'EVERCORE' },
    { code: '649', name: 'Skandia Operadora de Fondos, S.A. de C.V.', shortName: 'SKANDIA OPERADORA' },
    { code: '651', name: 'Segmentos Regionales de Crédito, S.A. de C.V.', shortName: 'CREDICAPITAL' },
    { code: '652', name: 'Más Fondos, S.A. de C.V., Sociedad Operadora de Sociedades de Inversión', shortName: 'MASFONDOS' },
    { code: '653', name: 'Solución Asea, S.A. de C.V., Sociedad Financiera Popular', shortName: 'SOLUCIÓN ASEA' },
    { code: '655', name: 'FinTech Innovation, S.A. de C.V., SOFOM ENR', shortName: 'FINTECH' },
    { code: '656', name: 'Unagra, S.A. de C.V., Sociedad Financiera de Objeto Múltiple, E.N.R.', shortName: 'UNAGRA' },
    { code: '659', name: 'ASP Integra OPC, S.A. de C.V.', shortName: 'ASP INTEGRA OPC' },
    { code: '670', name: 'Libertad Servicios Financieros, S.A. de C.V.', shortName: 'LIBERTAD' },
    { code: '677', name: 'Caja Popular Mexicana, S.C. de A.P. de R.L. de C.V.', shortName: 'CAJA POP MEXICANA' },
    { code: '678', name: 'Sólo Para Tí Service Sapi de CV', shortName: 'CRISTAL' },
    { code: '679', name: 'Fondo de inversión Banamex, S.A. de C.V.', shortName: 'FDO.BANAMEX' },
    { code: '680', name: 'Inmobiliaria Mex Arrendadora, S.A.', shortName: 'INMOBILIARIA' },
    { code: '681', name: 'Investa Bank, S.A., Institución de Banca Múltiple', shortName: 'INVESTA BANK' },
    { code: '682', name: 'Fondos de Inversión Afirme, S.A. de C.V.', shortName: 'FONDO AFIRME' },
    { code: '683', name: 'Caja Popular de Ahorros Tucari, S.C. de A.P. de R.L. de C.V.', shortName: 'CAJA TUCARI' },
    { code: '684', name: 'Fondos de Inversión Inbursa, S.A. de C.V.', shortName: 'INBURSA' },
    { code: '685', name: 'Fondos de Inversión Invex, S.A. de C.V.', shortName: 'FONDO INVEX' },
    { code: '686', name: 'Fondo Santander, S.A. de C.V.', shortName: 'FONDO SANTANDER' },
    { code: '687', name: 'Caja Popular La Providencia SC de AP de RL de CV', shortName: 'LA PROVIDENCIA' },
    { code: '688', name: 'Crédito Familiar, S.A. de C.V., SOFOM, E.N.R.', shortName: 'CRÉDITO FAMILIAR' },
    { code: '689', name: 'Fondo de Inversión Scotia, S.A. de C.V.', shortName: 'FONDO SCOTIA' },
    { code: '690', name: 'Fondos de Inversión Credit Suisse Operadora, S.A. de C.V.', shortName: 'CREDIT SUISSE FONDOS' },
    { code: '691', name: 'SPEI Digital, S.A.P.I. de C.V.', shortName: 'SPEI DIGITAL' },
    { code: '692', name: 'Mapfre Tepeyac S.A.', shortName: 'MAPFRE TEPEYAC' },
    { code: '693', name: 'Sociedad Financiera Inbursa, S.A. de C.V., SOFOM, E.R.', shortName: 'FINANCIERA INBURSA' },
    { code: '694', name: 'Fondo de Inversión Mifel, S.A. de C.V.', shortName: 'FONDO MIFEL' },
    { code: '695', name: 'Banco Inmobiliario Mexicano, S.A. Institución de Banca Múltiple', shortName: 'BIM' },
    { code: '696', name: 'OpeMapfre, S.A. de C.V.', shortName: 'OPEMAPFRE' },
    { code: '697', name: 'Actinver Afore, S.A. de C.V.', shortName: 'ACTINVER AFORE' },
    { code: '698', name: 'BNP Paribas México, S.A. de C.V.', shortName: 'BNP PARIBAS' },
    { code: '701', name: 'CLS Bank International', shortName: 'CLS' },
    { code: '704', name: 'Fondo HSBC, S.A. de C.V.', shortName: 'FONDO HSBC' },
    { code: '705', name: 'Fondos de Inversión Multiva, S.A. de C.V.', shortName: 'FONDO MULTIVA' },
    { code: '706', name: 'Sistema de Pagos Interbancarios CECOBAN S.A. de C.V.', shortName: 'CECOBAN' },
    { code: '710', name: 'Franklin Templeton Asset Mngmnt México S.A. de C.V.', shortName: 'FRANKLIN TEMPLETON' },
    { code: '715', name: 'Servicios PagoMóvil S.A. de C.V.', shortName: 'PAGOMOVIL' },
    { code: '901', name: 'Dirección de Disposición de Bienes INDEP', shortName: 'INDEP' },
    { code: '902', name: 'Financiera Nacional de Desarrollo Agropecuario Rural', shortName: 'FIRA' },
    { code: '903', name: 'CoDi Valida', shortName: 'CoDi Valida' },
    { code: '999', name: 'N/A', shortName: 'N/A' }
  ];

  for (const bank of banks) {
    await prisma.bank.upsert({
      where: { codigo: bank.code },
      update: {
        nombre: bank.name,
        nombreCorto: bank.shortName,
        activo: true
      },
      create: {
        codigo: bank.code,
        nombre: bank.name,
        nombreCorto: bank.shortName,
        activo: true
      }
    });
  }

  console.log('✅ Banks catalog seeded successfully');
};